             
CREATE MEMORY TABLE PUBLIC.CUSTOMER_ACCOUNT(
    CUSTOMER_ID BIGINT NOT NULL SELECTIVITY 100,
    ACCOUNT_CREATED_TIME DATE SELECTIVITY 1,
    CITY VARCHAR(255) SELECTIVITY 99,
    COUNTRY VARCHAR(255) SELECTIVITY 1,
    DOB DATE SELECTIVITY 1,
    EMAIL_ADDRESS VARCHAR(255) SELECTIVITY 100,
    FIRSTNAME VARCHAR(255) SELECTIVITY 84,
    HOME_PHONE_NUMBER VARCHAR(255) SELECTIVITY 80,
    LAST_LOGIN_TIME DATE SELECTIVITY 1,
    LASTNAME VARCHAR(255) SELECTIVITY 41,
    MOBILE_PHONE_NUMBER VARCHAR(255) SELECTIVITY 80,
    STATE VARCHAR(255) SELECTIVITY 5,
    STREET_ADDRESS VARCHAR(255) SELECTIVITY 100,
    ZIPCODE VARCHAR(255) SELECTIVITY 99
);     
ALTER TABLE PUBLIC.CUSTOMER_ACCOUNT ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(CUSTOMER_ID);               
-- 9992 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER_ACCOUNT;      
CREATE MEMORY TABLE PUBLIC.CUSTOMER_SUBSCRIPTION(
    SUBSCRIPTION_ID BIGINT NOT NULL SELECTIVITY 100,
    COUNTRY_ID INTEGER NOT NULL SELECTIVITY 1,
    CUSTOMER_ID BIGINT NOT NULL SELECTIVITY 100,
    IS_ACTIVE BOOLEAN NOT NULL SELECTIVITY 1,
    PLAN_END DATE SELECTIVITY 1,
    PLAN_PRICE DOUBLE NOT NULL SELECTIVITY 1,
    PLAN_START DATE SELECTIVITY 1,
    SERVICE_PLAN_ID INTEGER NOT NULL SELECTIVITY 1,
    UPDATE_PRICE_TIME DATE SELECTIVITY 1
);          
ALTER TABLE PUBLIC.CUSTOMER_SUBSCRIPTION ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(SUBSCRIPTION_ID);      
-- 9992 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER_SUBSCRIPTION; 
CREATE MEMORY TABLE PUBLIC.PRICE_BY_PLAN_COUNTRY(
    PRICE_ID BIGINT NOT NULL,
    COUNTRY_ID INTEGER NOT NULL,
    EFFECTIVE_FROM DATE SELECTIVITY 1,
    IS_ACTIVE BOOLEAN NOT NULL,
    LAST_UPDATED DATE SELECTIVITY 1,
    PRICE DOUBLE NOT NULL,
    SERVICE_PLAN_ID INTEGER NOT NULL
);  
ALTER TABLE PUBLIC.PRICE_BY_PLAN_COUNTRY ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(PRICE_ID);             
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.PRICE_BY_PLAN_COUNTRY;    
CREATE MEMORY TABLE PUBLIC.SERVICE_PLAN(
    PLAN_ID INTEGER NOT NULL,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255),
    NUMBER_OF_CONCURRENT_DEVICES_ALLOWED INTEGER NOT NULL
);       
ALTER TABLE PUBLIC.SERVICE_PLAN ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(PLAN_ID);       
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.SERVICE_PLAN;             
